[SC-34682] Add deployment pipeline and auto updates
Wellthy/docker-clamavd pull request #5
Opened 2022-10-11 19:07 UTC by cameron-wellthy

[SC-34682](https://app.shortcut.com/wellthy/story/34682)

## Overview
- Adds deployment pipeline
- Adds auto updates
- Test run: https://app.circleci.com/pipelines/github/Wellthy/docker-clamavd/20/workflows/932f0d9c-59ae-429f-a4f2-21fbb014dec5
- Updates Readme

## Developer Checklist

 ### `dependency changes`
 `DEPENDENCY` | `NEW VERSION` | `EXISTING VERSION`
----------- | ------------- | -------------
. | . | n/a

## Reviewer Checklist

- [ ] Read and contextualize the story

- [ ] Pull branch, manually test, verify AC are met

## Test Procedure

### `Verify file uploads work`
1. Go to any task
1. Try to upload any valid file
1. Make sure it works

### `Verify malware is detected`
1. Go to any task
1. Try to upload eicar.com.text file in the root level of this repository
1. Ensure it fails with an error "Sorry, xxx appears to contain malware"

## Release Procedure
Document how this will be deployed to:
- [ ] **Sandbox Environment**: *E.g. "I will manually follow the README steps to deploy to Aptible sandbox"
- [ ] **Staging Environment**:
- [ ] **Production Environment**:
- [ ] **Demo Environment**:

## Primary Considerations
*The Reviewer should make sure each of these is accounted for before approving this Pull Request. If any are deemed to be not applicable, check them off and move them to the "Not Applicable" section below.*

- [ ] **Dev environment**: Does it work in the development environment, with Dockerfile pointing to the local image?

- [ ] **Staging**: Can this be deployed to staging [Aptible] and tested there?

- [ ] **Production**: Who owns deploying this to production (or if automatically deployed, verifying in production)

- [ ] **Security**: Have dependency changes been reviewed for security?

### Not Applicable

- [ ] The following items are not applicable to this PR.

2022-10-12 08:34 UTC, stephenmelrose requested changes
Generally looking good! Like we're automating this. Just a few questions mostly.

2022-10-12 08:34 UTC, stephenmelrose commented on .circleci/config.yml
> +              source ./.circleci/update.sh; build_and_push_docker_image;
Any particular reason these two are on a single line? Multiline if we can for readability.

2022-10-12 08:34 UTC, stephenmelrose commented on .circleci/config.yml
> +  machine:
Could we use the Docker executer here? I think it's faster and cheaper than machine. We can use smaller `resource_class` too, which is probably where the cheap part comes in I think. I know we use machine everywhere, but I wonder if we should be looking at the docker executer when we can. Controversial take I know, and not required to be clear.

2022-10-12 08:34 UTC, stephenmelrose commented on .circleci/config.yml
> +  image: ubuntu-2004:202111-02
Should we look at [ubuntu-2204](https://circleci.com/developer/machine/image/ubuntu-2204)?

2022-10-12 08:34 UTC, stephenmelrose commented on .circleci/config.yml
> +          # change to latest
Does this comment need removing?

2022-10-12 08:34 UTC, stephenmelrose commented on .circleci/config.yml
> +      - hold_rollback:
Just to confirm, we queue up a rollback ready just in case? I like this approach if so. Interesting!

2022-10-12 08:34 UTC, stephenmelrose commented on .circleci/update.sh
> +deploy() {
This is an odd order to do this in... I'd do production and demo last at the very least.

Also, do we feel like we want/need some QA in any other environments before pushing to production/demo...?

2022-10-12 15:53 UTC, cameron-wellthy commented on .circleci/config.yml
> +      - hold_rollback:
Yeah it queues a roll back that requires manual approval to go through with. Open to alternatives but figured this would be a simple way in case anything goes wrong

2022-10-12 15:54 UTC, cameron-wellthy commented on .circleci/update.sh
> +deploy() {
We could, I thought about deploying to staging and then doing another approval step for deploying to the rest of the environments. Thoughts on that approach?

2022-10-13 10:06 UTC, stephenmelrose commented on .circleci/update.sh
> +deploy() {
That might be prudent... I'm trying to think about the discussion we'd have in the event we rolled out a "bad" ClamAV deploy. The question would be asked "did we test this?" for example. "Why if not?". If you get my drift.

2022-10-13 17:04 UTC, cameron-wellthy commented on .circleci/update.sh
> +deploy() {
Hmm what do you think about doing a deployment to staging, hold in circleci for manual review of how staging is working, then when approved it deploys to all other environments. For the roll back we can require an engineer to enable and push the rollback job to a PR instead of having the hold always in circleci?

2022-10-13 20:22 UTC, stephenmelrose commented on .circleci/update.sh
> +deploy() {
I think having a deploy to staging, hold, and then the rest is a good idea.

As for the latter question, I'm not sure I follow...? What do you mean a PR? Our other rollback jobs are just workflows we trigger manually with pipeline parameters. Are you proposing something different?

2022-10-13 20:40 UTC, cameron-wellthy commented on .circleci/update.sh
> +deploy() {
Oh pipeline parameters would be fine actually. I'll update with that

2022-10-14 08:03 UTC, stephenmelrose approved these changes
I'm going to approve this as I think we've achieved all feedback, but I also feel the need to point out a potential problem we've introduced.

As things stand we now update the Docker tag, deploy to staging, wait for testing, and deploy to production. But what if the production container has a problem while we're in the hold/testing phase and it requires a destroy and recreate?

In Aptible, this isn't actually a problem. Aptible make a copy of the Docker image and wouldn't pull any changes unless we explicitly sent them. But when we get into AWS, the production container would re-pull the latest image for the redeploy and we'd end up deploying the updated container before we intent to.

For ClamAV this is likely not too much of a problem. But this is specifically why for care-network I did environment specific "latest" tags, and it's why the wellthy.com repo does something similar using separate per environment repositories.

So to be clear, I'm not saying we need to massively refactor this now. But we may want to add a tech debt story to revisit this and implement a similar "latest" tagging and deploy model that other repos use.

2022-10-25 20:57 UTC, cameron-wellthy commented
This is now ready for deployment. I made some changes. It will now deploy to staging, hold for approval and testing and send a message to the team-core-engineering channel letting us know there's an update, once approved it will deploy to sandbox-1, sandbox-2, and demo, hold for approval and then deploy to production. Rollbacks are also in place.

2022-10-26 08:49 UTC, stephenmelrose commented
@cameron-wellthy Nice work on the updates. My call out would be the ordering of deployments... Firstly, demo is treated the same as production so we should deploy those together. Secondly, is there any value to deploying to sandbox 1 and 2 and then holding again? We've already deployed and tested to staging. Once we've tested I'd argue we're good to deploy everywhere else.

2022-10-26 14:05 UTC, cameron-wellthy commented
@stephenmelrose got it I'll update accordingly. I was just being overly careful with the holds

2022-10-27 08:23 UTC, stephenmelrose commented
"lower environments" 🤣 Re-approved.

2022-10-31 19:52 UTC, merged